### PR TITLE
status options + docs + general update

### PR DESCRIPTION
**Pull request by ghost**
- This pull request adds the feature for the user to configure the `status` & `readyState` of the request, in case that they have to do checks on the AJAX process.
- There is also now a `docs` folder for the GitHub Page(s) if a user wants to check it out on download; plus it just helps to keep all the together.
- All contributors have been included.
- Files, such as `README.md`, have been shortened and adjusted as needed.

_`docs` still has to be adjusted accordingly, which is currently a work in progress._

### CODE REVIEW

**Comment by flouthoc** [comment]
@ForgivenNin will try this out ASAP and let you know.

**Comment by ghost** [comment]
@flouthoc any suggestions/thoughts?

**Comment by flouthoc** [comment]
@ForgivenNin Everything else look fine , just wanted some input about why can't we have a detailed readme ?

**Comment by flouthoc** [comment]
Also you can squash the commits.

**Comment by ghost** [comment]
It is detailed; but it's just the same amount of information is presented in a far less amount of space.

How would I squash the commits? Doesn't that have to be done by the merge itself?

**Comment by ghost** [comment]
@flouthoc 
It appears that there are also two additional methods to `GET` & `POST`, which are `PUT` and `DELETE`. I haven't done anything with this yet, though, because I'm relatively new to AJAX (since it requires a server).

**Comment by ForgivenNin** [comment]
@flouthoc is there anything else that I should work on?

**Comment by ghost** [comment]
@flouthoc anything this could be applied to?
https://github.com/ForgivenNin/retrieve.js

**Comment by ghost** [comment]
@flouthoc Do you have any opinion about the pull request or anything else to be added?

**Pull request closed without merging**
